#!/bin/bash
#
# My .ssh/config looks like so:
# Host github-account1
#     HostName github.com
#     User git
#	  IdentityFile ~/.ssh/id_rsa_account1
# 	  #nick a1
# 	  #name account1
# 	  #email account1@gmail.com
#
# Host github-account2
#     HostName github.com
#     User git
#	  IdentityFile ~/.ssh/id_rsa_account2
# 	  #nick a2
# 	  #name account2

[ -z "$1" ] && echo "Missing nickname" && exit 
[ -z "$2" ] && echo "Missing repo" && exit 

identity=$( awk -v id=$1 '
			$1 == "Host"	{ host = $2; next; } 
			$1 == "#nick"	{ nick = $2; next; } 
			$1 == "#name"	{ name = $2; next; } 
			$1 == "#email"	{ 
			$1 = ""; 
			sub( /^[[:space:]]*/, "" ); 
				if( nick == id ) {
					print nick, name, $0, host;
				}
			}' ~/.ssh/config )

[ -z "${identity}" ] && \
	echo "Nickname not in ~/.ssh/config" && exit 

read -a values <<< ${identity}

name=${values[1]}
email=${values[2]}
host=${values[3]}

set -x
touch README.md
git init
git config user.name ${name}
git config user.email ${email}
git add README.md
git commit -m "first commit"
git remote add origin ssh://${host}/${name}/${2}.git
git push -u origin master


